add scalar substition support (#9)
* substitution draft

- works for ports
- detects unbound variables
- integrated in apply

* fix error message, update help message

* CR

* support delete, add tests

* use multiple --set syntax, as discussed.

* add conflicting --set checks

example:
```
22-08-03 scott@pavillion cli % ./dist/signadot_darwin_arm64/signadot --debug sandbox apply -f ~/Dev/signadot/cliv2-test/sb.json --set name=bb --set cluster=minikube --set name=z --set cluster=c
Error: conflicting variable defs:
	cluster: c, minikube
	name: z, bb
```

* CR

- fix up the re-do of delete with --set
- bug fix in subst conflict check
- more readable array case of port2int